- name: Copy docker-compose file
  copy:
    src: docker-compose.yaml
    dest: /home/ec2-user/docker-compose.yaml

- name: Docker login
  docker_login:
    registry_url: "{{ docker_registry }}"
    username: "{{ docker_username }}"
    password: "{{ docker_password }}"

- name: Start container from compose
  docker_compose:
    project_src: /home/ec2-user
    # state: present # docker-compose up # default state so no need to specify